# Generated by Django 5.0.6 on 2024-07-01 03:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='votation.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Diputados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('ocup', models.CharField(blank=True, default='Sin Cargo', max_length=25, verbose_name='Ocupación')),
                ('descrip', models.TextField(blank=True, default='Sin Descripcion', max_length=200, verbose_name='Descripción')),
                ('imagen', models.ImageField(default='nopicture.jpg', upload_to='images/', verbose_name='Imagen')),
                ('votos', models.IntegerField(blank=True, default=0, verbose_name='Votos')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Diputado', to='votation.municipio')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votation.provincia', verbose_name='Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('ci', models.CharField(max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11), django.core.validators.MaxLengthValidator(11)], verbose_name='CI')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('voto', models.BooleanField(blank=True, default=False, verbose_name='Voto')),
                ('is_active', models.BooleanField(default=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Persona', to='votation.municipio')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votation.provincia', verbose_name='Provincia')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
