# Generated by Django 5.0.6 on 2024-07-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diputados',
            old_name='edad',
            new_name='age',
        ),
        migrations.RemoveField(
            model_name='diputados',
            name='descrip',
        ),
        migrations.RemoveField(
            model_name='diputados',
            name='ocup',
        ),
        migrations.AddField(
            model_name='diputados',
            name='biografia',
            field=models.TextField(blank=True, default='Sin Descripcion', max_length=3000, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='diputados',
            name='cargo',
            field=models.CharField(blank=True, default='Sin Cargo', max_length=100, verbose_name='Ocupación'),
        ),
    ]
